### ISSUE TITLE
f-string error on backup execution - line 43

### ISSUE THREAD

**Issue by netpres** [Tetrax-10/reddit-backup-restore#1]
Completed setup per readme.md

On execution I see this

`File "X:\reddit-backup-restore\backup.py", line 43

print(f"Backed up {len(backup["subreddits"])} subscribed subreddits.")
                                                ^^^^^^^^^^
SyntaxError: f-string: unmatched '['`

**Comment by Tetrax-10** [comment]
Fixed it, thanks for reporting. It should work now.

**Comment by netpres** [comment]
Working perfectly.
