### ISSUE TITLE
Download the saved media?

### ISSUE THREAD

**Issue by chuvak889** [Tetrax-10/reddit-backup-restore#2]
Hello. Thanks for the tool. I got banned so i decided to backup my stuff.  
I was wondering, is there a way to easily download all the saved posts/videos/images i had saved on reddit?

**Comment by Tetrax-10** [comment]
With this tool you can only backup and restore items (transfer to a new account). You can't download the actual contents with this.

You can try these tools:

https://github.com/shadowmoose/RedditDownloader
https://github.com/aliparlakci/bulk-downloader-for-reddit
