### ISSUE TITLE
[Feature] Regular Backups

### ISSUE THREAD

**Issue by starsoccer** [Tetrax-10/reddit-backup-restore#3]
Any plans to add support for having this script run regularly? Ideally I was thinking about putting it in a docker container and then having it run once a week or something like that to backup things.

**Comment by Tetrax-10** [comment]
Currently, there are no plans to implement automatic backup/restore within this project. For regular backups, I use `Task Scheduler` on Windows. On Linux and macOS, you can achieve similar functionality using `cron` and `launchd`, respectively.
